title: "[Project Proposal] "
labels: ["Project Proposal"]
body:
  - type: textarea
    attributes:
      label: "What is your Project Idea?"
      value: |
        Explain your idea here.

        FYI @sonatype-nexus-community/community-leaders
